name: Archive

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Archive.yml'
  schedule:
    - cron: '0 4 1 * *' # At 04:00 on the first day of the month
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Script
        run: external/Phi/scripts/ci/ArchiveAllLinks.sh
