name: Benchmark

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Benchmark.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: false

      matrix:
        compiler:
          - "clang-18"
          - "gcc-14"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ matrix.compiler }}

      - name: Setup Environment
        run: external/Phi/scripts/ci/SetupEnvironment.sh

      - name: Install compiler
        run: external/Phi/scripts/ci/InstallTools.sh ${{ matrix.compiler }} ninja

      - name: Install dependencies
        run: sudo scripts/ci/InstallDependencies.sh

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          cmake -DCMAKE_AR=${AR_EXECUTABLE} -DCMAKE_BUILD_TYPE:STRING="Release" -DDLXEMU_BUILD_BENCHMARKS:BOOL=ON -DDLXEMU_BUILD_TESTS:BOOL=OFF ..

      - name: Build
        working-directory: ./build
        run: cmake --build . --config Release

      - name: Disabling CPU Frequency Scaling
        continue-on-error: true
        run: |
          # Reference https://github.com/google/benchmark/blob/main/docs/user_guide.md#disabling-cpu-frequency-scaling
          sudo cpupower frequency-set --governor performance

          # Verify it worked
          sudo cpupower frequency-info -o proc

      - name: Run benchmark
        working-directory: ./build
        run: ./bin/DLXLibBenchmark --benchmark_repetitions=20 --benchmark_enable_random_interleaving=true --benchmark_out=base_benchmark.json --benchmark_out_format=json --benchmark_display_aggregates_only=true

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: base_benchmark_${{ matrix.compiler }}.json
          path: build/base_benchmark.json
