name: Deploy

on:
  push:
    branches:
      - main

jobs:
  gh_pages:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: "2"
      EM_CACHE_FOLDER: 'emsdk-cache'
      EM_VERSION: "2.0.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v8
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Install cmake
        uses: lukka/get-cmake@v3.19.2

      - name: Build
        run: |
          mkdir -p build
          cd build

          emcmake cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
          emmake cmake --build . --clean-first --target DLXEmu

          mv bin/DLXEmu.html bin/index.html

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3.0.2
        with:
          gpg-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/bin
          git-config-name: AMS21Bot
          git-config-email: AMS21Bot.github@gmail.com
