name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  gh_pages:
    runs-on: ubuntu-20.04

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: "2"
      EM_CACHE_FOLDER: 'emsdk-cache'
      EM_VERSION: "2.0.18"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: main
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Install dependencies
        run: |
          sudo apt-get install xorg-dev libglu1-mesa-dev libxrandr-dev

      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1

      - name: Build main
        run: |
          mkdir -p build
          cd build

          emcmake cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
          emmake cmake --build . --clean-first --target DLXEmu

          mv bin/DLXEmu.html bin/index.html

          # Copy to output directory
          mkdir -p $GITHUB_WORKSPACE/output
          cp -r bin/* $GITHUB_WORKSPACE/output

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: develop
          submodules: recursive
          path: develop
      
      - name: Build develop
        run: |
          cd develop
          mkdir -p build
          cd build

          emcmake cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-DPHI_DEBUG"
          emmake cmake --build . --clean-first --target DLXEmu

          mv bin/DLXEmu.html bin/index.html

          # Copy to output directory
          mkdir -p $GITHUB_WORKSPACE/output/staging
          cp -r bin/* $GITHUB_WORKSPACE/output/staging

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_KEY_PASSPHRASE }}
          git_user-signingkey: true
          git_commit-gpgsign: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: output
          git-config-name: AMS21Bot
          git-config-email: AMS21Bot.github@gmail.com
