name: Emscripten

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Emscripten.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
    tags:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-24.04

    env:
      EM_CACHE_FOLDER: 'emsdk-cache'

    strategy:
      fail-fast: false

      matrix:
        em_version:
          - "3.1.61"
          - "2.0.31"

        build_type:
          - "Debug"
          - "RelWithDebInfo"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        # Continue on error to ignore problems with caching
        continue-on-error: true
        with:
          version: ${{ matrix.em_version }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Setup Environment
        run: external/Phi/scripts/ci/SetupEnvironment.sh

      - name: Install ninja
        run: external/Phi/scripts/ci/InstallTools.sh ninja

      - name: Install dependencies
        run: sudo scripts/ci/InstallDependencies.sh

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          emcmake cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="-DDLXEMU_VERIFY_UNDO_REDO -DDLXEMU_VERIFY_COLUMN" ..

      - name: Build
        working-directory: ./build
        run: emmake cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}
